### ISSUE TITLE
Wind propagation of thermals not working correctly

### ISSUE THREAD

**Issue by philipoe** [alexferrer/xplane_thermals#19]
The thermal updrafts are not shifted correctly by the X-Plane global wind. However, they are drawn correctly.

Steps to reproduce the problem: 
 - Set wind in X-plane to some magnitude and direction 0 (this represents wind from the north). 
 - The thermals will be drawn correctly, i.e. they will be carried towards the south
 - There is no lift to be found when one flies close to the drawn thermals. In fact the actual lift will be shifted only to the WEST instead of to the south.

First hints:
 - In line https://github.com/alexferrer/xplane_thermals/blob/master/thermal_model.py#L97 , dX is defined as the delta in LATITUDE. 
 - However, in https://github.com/alexferrer/xplane_thermals/blob/master/thermal_model.py#L31, dX is then calculated proportionally to the sine of the wind direction. Therefore, when setting wind direction in X-Plane to zero, this line yields dX=0, although it should be nonzero. This would need to be the cosine!
 - However, despite the sine/cosine issue, the drawing of the thermals still works correctly, so there might be some other twist/issue somewhere there?

@alexferrer Have you observed this, too? If so, you probably know best where the actual issue is. Otherwise I will look into it in the coming days.

**Comment by alexferrer** [comment]
Looking at the revision history I see I changed it *and* tested it.. If i recall right, at some point I had the same error drive me crazy, so I just flipped the drift formula to "get it to work".. 

https://github.com/alexferrer/xplane_thermals/commit/ecb10d4b29c553fa1be354eae64540319f7f9e5c

I wonder if it has to do with  the XPLMWorldToLocal function that returns the local reference for graphics purposes. 

At this moment I don't have access to my Xplane machine (fast) to test.. if you want to look into it it would be great.!

**Comment by philipoe** [comment]
Hi, unfortunately I am quite short on time at the moment, too. I "hacked" it (and it works perfectly then, but is definitely not the right thing to do, so one needs to re-assess this) by exchanging dX and dY at https://github.com/alexferrer/xplane_thermals/blob/master/thermal_model.py#L98 .

**Comment by alexferrer** [comment]
Fixed by reversing the wind drift vector. Tested ok.
