### ISSUE TITLE
Jerks in applied roll when in thermal

### ISSUE THREAD

**Issue by philipoe** [alexferrer/xplane_thermals#20]
Jerks in the applied roll value (https://github.com/alexferrer/xplane_thermals/blob/master/thermal_model.py#L129) are observed when in a thermal. This seems to come from the rounding applied when calculating the left/right wing positions at https://github.com/alexferrer/xplane_thermals/blob/master/thermal_model.py#L108 . I removed the int() and the round() and it works very smootly. 

Why was the int() and round() needed? Could that be removed? Should I submit a PR or do you quickly want to do it?

**Comment by alexferrer** [comment]
Please go ahead and check-in the changes to git.

I don't like to do checkins on git unless I have tested the changes and at
the moment I don't have access to my test machine.

**Comment by alexferrer** [comment]
At a very early prototype of the plugin, i used a 3D matrix to represent
lift strength on the map.. I am guessing that to use that, I had to have an
integer I could plug into the matrix.. I am guessing.
It is no longer needed, so i removed, tested and checked in.

Thx for finding the issue!

Alex.

**Comment by alexferrer** [comment]
Done, tested.
