### ISSUE TITLE
Does this plug-in work in X Plane 11 too?

### ISSUE THREAD

**Issue by MalteFlender** [alexferrer/xplane_thermals#26]
I wonder if this plug-in works in X Plane 11.
If it is not working, do you have any plans to expand it to do so?

**Comment by alexferrer** [comment]
I have not got a full copy of X plane 11 yet.. maybe in the future.

**Comment by robustini** [comment]
Here work on X-Plane 11.34.

**Comment by alexferrer** [comment]
Tested. It works
